### PR TITLE
mets_adapter terraform stack

### PR DESCRIPTION
**Pull request by warrd**
Just ECR for now.

### CODE REVIEW

**Comment by jamieparkinson** [comment]
Perhaps, given this is a new stack, it would be worth trying to do it with TF 0.12? Haven't checked compatibility of the existing ECR module but Alex's work might be a good reference

**Comment by jamesgorrie** [comment]
[The ECR module does nothing](https://github.com/wellcometrust/terraform-modules/tree/master/ecr).

The issue with putting this into `tf0.12` is that when it comes to adding the service (and everything that comes with ECS) you will have to keep using `12`, and thus convert those modules.

Not saying don't do it, but be aware of the work that awaits.

**Comment by alicefuzier** [comment]
Have we agreed a strategy to migrate to 12?

**Comment by warrd** [comment]
:+1: reckon going to stick to 11 because of the above, and the fact that I'll have to install 2 versions of Terraform on my machine or have to use docker to run `terraform apply`.

**Pull request merged**
