### PR TITLE
Binding information note

### PR DESCRIPTION
**Pull request by warrd**
## Issue

https://github.com/wellcometrust/platform/issues/3995

## Description

Instead of appending Marc 563 to `physicalDescription` field, instead pull it out into a `binding-information` note, as we do with other 5XX fields.

### CODE REVIEW

**Comment by jamesgorrie** [comment]
@jtweed this is a 300 field and the frontend uses it - why are we putting it as a note?

**Comment by warrd** [comment]
@jtweed that makes sense. Shall we use the name `BindingInformation` for the new note type, for consistency with the marc field naming?

**Comment by jtweed** [comment]
Sounds good 👍

**Comment by warrd** [comment]
@jtweed suggested in https://github.com/wellcometrust/catalogue/pull/216#issuecomment-547522683 that

> I think we probably want to join subfields with spaces, but create multiple entries in contents for repeated fields?

This doesn't appear to be done yet so gonna add another commit as part of this PR, if everyone thinks that's the correct strategy?

**Comment by warrd** [comment]
Have done the above

**Pull request merged**
