### PR TITLE
Docs via Gitbook

### PR DESCRIPTION
**Pull request by jamesgorrie**
[Demo](https://wellcomecollection.gitbook.io/catalogue/v/docs/)

As we've been given charitable status for Gitbooks, we thought it might be useful to use them as a knowledge base, specifically focussing on search relevance, but not exclusively to.

This _must_
* Address general discoverability of the docs
* Address discoverability of the content within the docs
* Allow for review of content before being pushed into master
* Allow for search
* Be SEO friendly

This _should / might_:
* Provide a more non-github user friendly way to edit docs
* Build navigation automatically

### CODE REVIEW

**Comment by kenoir** [comment]
Very nice. What's the non-github-code-editing method of editing?

**Comment by jamesgorrie** [comment]
@kenoir 
> What's the non-github-code-editing method of editing?

I _think_ gitbook.

It has a block type editor and can push to branches that can then be reviewed and merged. Which is great as a requirement is for docs to be reviewed.

**Comment by jamesgorrie** [comment]
Once this is in, I will give it a go, and write a little guide as to how.

**Comment by harrisonpim** [comment]
😍 love this!

**Pull request merged**
